## 1. Warm-up: Rebuild the basics
**Goal:** Make array creation and inspection feel automatic.
1. Create each of the following arrays and print its `shape`, `ndim`, and `dtype`:
   - A 1D array of integers from 10 to 19  
   - A 2D array of shape `(4, 3)` filled with 1.5  
   - A 3D array of zeros with shape `(2, 2, 3)`

2. Convert the `(4, 3)` float array to integers using `.astype(int)`.  
3. Write down (in a markdown cell) when you would prefer `float` vs `int` in real analyst work (e.g., prices vs counts).


In [ ]:
import numpy as np

#1 
arr_1d = np.arange(10, 20)          # 1D array of integers from 10 to 19
print(f"1D Array: {arr_1d}")        # Print the 1D array
print(f"Shape: {arr_1d.shape}, Dimensions: {arr_1d.ndim}, Data Type: {arr_1d.dtype}") # Print shape, dimensions, and data type

arr_2d = np.full((4,3), 1.5)       # 2D array of shape (4, 3) filled with 1.5
print(f"\n2D Array:\n {arr_2d}")    # Print the 2D array
print(f"Shape: {arr_2d.shape}, Dimensions: {arr_2d.ndim}, Data Type: {arr_2d.dtype}") # Print shape, dimensions, and data type

arr_3d = np.zeros((2, 3, 4))
print(f"\n3D Array:\n {arr_3d}")    # Print the 3D array
print(f"Shape: {arr_3d.shape}, Dimensions: {arr_3d.ndim}, Data Type: {arr_3d.dtype}") # Print shape, dimensions, and data type

#2
# Convert the data type of the 2D array from float to int32
arr_2d_int32 = arr_2d.astype(np.int32)
print(f"\n2D Array data type is converted from float to int32: {arr_2d_int32.dtype}")


3. 
Integer is preferred when working with discrete values such as counts of items, people, number of items sold etc. These type of values are whole numbers and do not require decimal points.

Float is preferred when working with continuous values such as prices, measurements, percentages etc. These type of values often require decimal points to represent the data precisely.


## 2. Sales table drill: Indexing and slicing

**Scenario:** You have quarterly sales numbers for 4 regions (rows) over 5 quarters (columns).

Do the following:

1. Select all quarters for **Region B** as a 1D array.  
2. Select **Q2 to Q4** (inclusive) for all regions as a 2D subarray.  
3. Select **Q5** sales for **Regions A and D only** (use slicing or fancy indexing).  
4. Compute the **shape** of each result and add a brief comment: “Is this 1D or 2D, and why?”

In [ ]:
import numpy as np

sales = np.array([
    [200, 220, 250, 270, 300],  # Region A
    [150, 160, 170, 180, 190],  # Region B
    [300, 310, 320, 330, 340],  # Region C
    [400, 420, 440, 460, 480]   # Region D
])

print(f"Region B sales (1D array): {sales[1, :]}")  # 1D array for Region B
print(f"Sahpe of Region B sales: {sales[1,:].shape}")  
# This is 1D because we are selecting only single row [index 1] which is Region B and all columns.

print(f"\nQ2 to Q4 sales for all regions (2D subarray):\n {sales[:, 1:4]}")  # 2D subarray for Q2 to Q4
print(f"Shape of Q2 to Q4 sales: {sales[:, 1:4].shape}")
# This is 2D because we are selecting all rows and multiple columns [index 1 to 3] which correspond to Q2 to Q4.

print(f"\nQ5 sales for Regions A and D only: {sales[[0, 3], 4]}")  # Q5 sales for Regions A and D
print(f"Shape of Q5 sales for Regions A and D: {sales[[0, 3], 4].shape}")
# This is 1D because we are selecting specific rows [index 0 and 3] which correspond to Regions A and D and a single column [index 4] which is Q5.
# In Numpy, whenever we use a single integer to index an axis, the axis is "collapsed", resulting in a lower-dimensional array. The result is flattened to 1D.


## 3\. Boolean masks: Work with targets

**Scenario:** You have campaign response data.

```py
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue
```

1. Compute the **ROI** for each person: `roi = revenue / spend`.  
2. Create a boolean mask for customers with `roi >= 2.0`.  
3. Use the mask to:  
   - List their names  
   - List their spend and revenue  
4. Create a second mask for customers with `spend >= 200`.  
5. Combine the two masks to find customers who have **roi \>= 2.0 AND spend \>= 200**.  
6. In a markdown cell, answer: *“What business insight do you get from this filtered group?”*

In [ ]:
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue

#1
roi = revenue / spend
print(f"ROI for each customer:\n {np.round(roi, 2)}") # Print ROI rounded to 2 decimal places

#2
roi_above_2_name = names[roi >= 2]
roi_above_2_spend = spend[roi >= 2]
roi_above_2_revenue = revenue[roi >= 2]
print(f"\nCustomers with ROI above 2:\n {roi_above_2_name}")
print(f"Corresponding Spend:\n {roi_above_2_spend}")
print(f"Corresponding Revenue:\n {roi_above_2_revenue}")

#3
customer_roi_spend = names[np.isin(names, roi_above_2_name) & (spend >= 200)] # Customers with ROI above 2 and Spend above 200
print(f"\nCustomers with ROI above 2 and Spend above 200:\n {customer_roi_spend}")

# Business Insight:
# Customers with ROI above 2 are generating at least double the revenue compared to their marketing spend. 
# Focusing marketing efforts on these customers could lead to higher overall profitability. 


# Business Insight:
* Customers with ROI above 2 are generating at least double the revenue compared to their marketing spend. 
* Focusing marketing efforts on these customers could lead to higher overall profitability. 

## 4\. Gradebook: Aggregations and broadcasting

Reuse the “Gradebook” idea from class and extend it.

```py
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])
```

1. Compute each student’s **average score** (per row).  
2. Compute each subject’s **average score** (per column).  
3. Create `scores_centered` by subtracting the **subject mean** from each column (broadcasting).  
4. For `scores_centered`, compute per-student averages again.  
5. Compare which student looks best by **raw average** vs **centered average**.  
6. In a markdown cell, explain briefly why centered scores might give a fairer comparison.

In [ ]:
import numpy as np

students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

# Compute average per student (axis 1 = horizontal across columns)
student_averages = np.mean(scores, axis=1)
# Pair them up for a clear report
for student, avg in zip(students, student_averages):    # the zip function pairs each student with their average score
    print(f"{student} Average: {avg:.2f}")

print("\n")     # Newline for better readability

# Compute average per subject (axis 0 = vertical down rows)
sub_averages = np.mean(scores, axis=0)  
# Pair them up for a clear report
for subject, avg in zip(subjects, sub_averages):        # the zip function pairs each subject with its average score
    print(f"{subject} Average: {avg:.2f}")              

scores_centered = scores - np.mean(scores, axis=0)  # Centering scores by subtracting subject mean
print(f"\nCentered Scores:\n {np.round(scores_centered, 2)}")

avg_score_centred_student = np.mean(scores_centered, axis=1)  # Average of centered scores for each student
print(f"\nScores_centred average for each student: {np.round(avg_score_centred_student, 2)}")

S1 Average: 80.00
S2 Average: 65.00
S3 Average: 90.00
S4 Average: 81.67
S5 Average: 73.33


Math Average: 75.40
Stats Average: 76.80
Python Average: 81.80

Centered Scores:
 [[ -0.4   3.2   3.2]
 [-15.4 -11.8 -11.8]
 [ 14.6  11.2  10.2]
 [  6.6   2.2   2.2]
 [ -5.4  -4.8  -3.8]]

Scores_centred average for each student: [  2.   -13.    12.     3.67  -4.67]


# Why Centered Scores are Fairer:
* Centered scores account for variations in subject difficulty by normalizing scores based on the average performance in each subject. This allows for a fairer comparison of student performance across different subjects, as it highlights how well a student performed relative to their peers in each subject rather than just looking at raw scores which may be influenced by the inherent difficulty of the subject.

## 5\. Reshape and flatten: From daily to weekly

**Scenario:** You have 30 days of daily website visits, and you want to summarize them by week.

```py
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])
```

1. Reshape `daily_visits` into a `(6, 5)` array representing **6 weeks × 5 days**.  
2. Compute **total visits per week**.  
3. Compute **average visits per day of the week** (e.g., all “day 1 of week” together, all “day 2 of week” together, etc.).  
4. Flatten the reshaped array back to 1D and confirm it matches the original `daily_visits`.

Hint: Pay attention to how reshaping groups the data; mention any assumptions you’re making about which days belong to which week.

In [ ]:
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])

reshaped_daily_visits = daily_visits.reshape((6,5)) # Reshape into 6 weeks (rows) and 5 days (columns)
print(f"Resahpe daily visits into weeks x days:\n {reshaped_daily_visits}")

total_visits_per_week = np.sum(reshaped_daily_visits, axis=1)  # Total visits per week
print(f"\nTotal visits per week:\n {total_visits_per_week}")

avg_visits_per_day = np.mean(reshaped_daily_visits, axis=0)  # Average visits per day across weeks
print(f"\nAverage visits per day across weeks:\n {np.round(avg_visits_per_day, 2)}")

daily_visits_flat = reshaped_daily_visits.flatten()  # Flatten back to 1D array
print(f"\nFlattened daily visits array:\n {daily_visits_flat}")

# Data integrity check using element-wise comparison
data_check = daily_visits_flat == daily_visits
print(f"\nData integrity check (should be all True):\n {data_check}")

## 6\. Mini-project: Simple scoring model

This mirrors the tiny matrix multiply example from class, but with more features.

```py
# Each row: [page_views, time_on_site (minutes), past_purchases]
X = np.array([
    [10,  3.5,  0],
    [25,  5.0,  1],
    [40,  2.0,  0],
    [15, 10.0,  3],
    [30,  4.0,  2]
])

customers = np.array(["C1", "C2", "C3", "C4", "C5"])
```

1. Choose a weight vector `w = [w_views, w_time, w_purchases]` (for example `[0.1, 0.5, 1.0]`).  
2. Compute a **score** for each customer using `scores = X @ w`.  
3. Rank customers by score (highest first).  
4. Change the weights to emphasize **past_purchases** more than other features, and recompute.  
5. In a markdown cell, answer:  
   - Which customer is top-ranked before vs after changing weights?  
   - In what real-world situation might you prefer each weighting?

In [ ]:
X = np.array([
    [10,  3.5,  0],
    [25,  5.0,  1],
    [40,  2.0,  0],
    [15, 10.0,  3],
    [30,  4.0,  2]
])

customers = np.array(["C1", "C2", "C3", "C4", "C5"])

w1 = np.array([0.1, 0.5, 1.0]) #Define weight vector

scores1 = X @ w1                        # Matrix multiplication to get weighted scores
print(f"Weighted scores for each data point:\n {np.round(scores1, 2)}")
# agrsort() get indices that would sort the weighted scores in descending order
#[::-1] -> 1st ":" refers to start; 2nd ":" refers to end; 3rd "-1" reverses the order
rank = np.argsort(scores1)[::-1]      
ranked_customers = customers[rank]      # Rank customers based on weighted scores
print(f"\nRanked customers based on weighted scores:\n {ranked_customers}")

w2 = np.array([0.1, 0.5, 7.0])           # New weight vector with higher weight on the third feature

scores2 = X @ w2                        # Matrix multiplication to get weighted scores with new weights
print(f"\nWeighted scores for each data point with new weights:\n {np.round(scores2, 2)}")
rank2 = np.argsort(scores2)[::-1]       # Get indices that would sort the weighted scores in descending order
ranked_customers2 = customers[rank2]    # Rank customers based on weighted scores with new weights
print(f"\nRanked customers based on new weighted scores:\n {ranked_customers2}")


* Which customer is top-ranked before vs after changing weights?
1. Before changing weights, the top-ranked customer is C4, who has a high time on site and multiple past purchases.
2. After changing weights to emphasize past purchases more, the top-ranked customer becomes C4 again, as they have the highest number of past purchases.

* In what real-world situation might you prefer each weighting?
1. The initial weighting might be preferred in scenarios where overall engagement (time on site and page views) is more important, such as for ad revenue models.
2. The adjusted weighting would be more suitable for scenarios focused on customer loyalty and repeat business, such as subscription services or membership programs.

## 7\. Stretch ideas (optional)

If you’re comfortable with the above, try:

- Generate 1,000 random test scores with `np.random.randn`, scale them to have mean 70 and standard deviation 10, then:  
  - Clip scores to the range `[0, 100]`  
  - Compute min, max, mean, and standard deviation  
- Simulate a small A/B test:  
  - Two groups of 20 users each  
  - Randomly generate conversions (0 or 1\) for each group  
  - Compute conversion rate per group using pure NumPy operations


In [ ]:
scores = np.random.randn(1000)

scaled_scores = (10 * scores) + 70      # Scale to mean 70 and stddev 10
print(f"\nScaled scores with mean 70 and stddev 10:\n {scaled_scores}")

# np.clip(scaled_scores, 0, 100) acts as a safety boundary. 
# It forces every number in the array to stay within a specific range (in this case, between 0 and 100).
ranged_scores = np.clip(scaled_scores, 0, 100) 
print(f"\nRanged scores between 0 and 100:\n {ranged_scores}")

print(f"\nMinimum score: {np.min(ranged_scores)}")   # Minimum score
print(f"Maximum score: {np.max(ranged_scores)}")     # Maximum score
print(f"Mean score: {np.mean(ranged_scores)}")       # Mean score
print(f"Standard Deviation: {np.std(ranged_scores)}") # Standard Deviation

## Don't understand the 2nd part of the question

- Simulate a small A/B test:  
  - Two groups of 20 users each  
  - Randomly generate conversions (0 or 1\) for each group  
  - Compute conversion rate per group using pure NumPy operations