# This is a markdown cell.

In [5]:
import sys
print("Python location", sys.executable)
print("Python version", sys.version)

Python location /Users/ccheng/miniconda3/envs/pds/bin/python
Python version 3.10.19 (main, Oct 21 2025, 16:37:10) [Clang 20.1.8 ]


# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [8]:
import numpy as np
# np.arrange creates a NumPy array with values 0 to n-1, 0 to 999,999
my_arr = np.arange(1_000_000)

#check the length of the array
print(f"Length of my_arr: {len(my_arr)}")

#print first 5 elements of the array
#slicing syntax: array[start:end:step], end index is exclusive
print("First 5 elements of my_arr:", my_arr[0:5])
#print last 5 elements of the array
print("Last 5 elements of my_arr:", my_arr[-5:])
my_list = list(range(1_000_000)) 

print("NumPy Vectorized Multiplication (my_arr * 2):")
#Vecorized multiplication means applying an operation to the entire array at one instead looping through each element
%timeit my_arr2 = my_arr * 2 

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list] 

Length of my_arr: 1000000
First 5 elements of my_arr: [0 1 2 3 4]
Last 5 elements of my_arr: [999995 999996 999997 999998 999999]
NumPy Vectorized Multiplication (my_arr * 2):
534 μs ± 27.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
15.7 ms ± 350 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


- Numpy operation took 535 microseconds per loop
- Python list comprehension took 15.6ms per loop
- NumPy is approximately 29 times faster than Python lists for this operation.

## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension. (2, 4) means 2 rows and 4 columns.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [7]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [9]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### [EXERCISE 1: Creation & Casting]
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [ ]:
#1
ones_array = np.ones((3,4))
print("3x4 array of ones:", ones_array)
print("DType of ones_array:", ones_array.dtype)

#2
ones_float32 = ones_array.astype(np.float32)
print("\nCasted to float32:\n", ones_float32)
print("DType of ones_float32:", ones_float32.dtype)

#3
str_arr = np.array(['1.25', '-9.6', '42'])
float_array = str_arr.astype(np.float64)
print("\nCasted to float64:", float_array)


3x4 array of ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
DType of ones_array: float64

Casted to float32:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
DType of ones_float32: float32

Casted to float64: [ 1.25 -9.6  42.  ]


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [27]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


- Operations apply to entire arrays at once.
- arr * arr multiples element by element (NOT matrix multiplication).
- No loops needed in your code!

[[1, 2, 3]
 [4, 5, 6]] + 5
 
 [[[1+5, 2+5, 3+5]
  [4+5, 5+5, 6+5]]] = 

[[6, 7, 8]
 [9, 10, 11]]

## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [28]:
# [DEMO] Slicing views
arr = np.arange(10)
print("Original array:", arr)
# [start:stop:step], default [0:end:1]
arr_slice = arr[5:8] #slice from index 5 to 7 with step 1
arr_slice[1] = 12345 #modify the slice. arr_slice[1] corresponds to arr[6]
print("Original array modified via slice:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]


In [29]:
# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
# :2 means rows 0 and 1 (2 is exclusive)
# 1: means columns 1 to end
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])


First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### [EXERCISE 2: The Logic of Slicing]
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [47]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# select the frist column of arr2d using slicing
#first_col = arr2d[:, 0]
first_col2 = arr2d[:, :1]  # keep the 2D structure; [:, :1] mean all rows, columns up to (but not including) index 1
print("\nFirst column of arr2d:\n", first_col2)

# set all elements in the second row to 0
arr2d[1,:] = 0
print("\narr2d after setting second row to 0:\n", arr2d)


First column of arr2d:
 [[1]
 [4]
 [7]]

arr2d after setting second row to 0:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]


In [ ]:

print("\narr2d[1]:", arr2d[1].shape)
print("\narr2d[1,:]:", arr2d[1,:].shape)



arr2d[1]: (3,)

arr2d[1,:]: (3,)


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [3]:
import numpy as np

In [4]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

# A mask is a boolean array that indicates whether each element meets a certain condition
bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
# score[bob_mask] selects the rows in scores where the corresponding value in bob_mask is True
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### [EXERCISE 3: Complex Filtering]
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [7]:
#1
bob_mask = (names != 'Bob')
print("Mask for names not equal to 'Bob':", bob_mask)
print("Scores of people not named Bob:\n", scores[bob_mask])

#2
bob_mask = (names == 'Bob') | (names == 'Will')
print("\nMask for names equal to 'Bob' or 'Will':", bob_mask)
print("Scores of people named Bob or Will:\n", scores[bob_mask])

#3
scores_less_than_80 = (scores < 80)
score_below_80 = scores[scores_less_than_80]
print("\nMask for scores less than 80:\n", scores_less_than_80)

scores[scores_less_than_80] = 0
print(f"Score after setting scores less than 80 to 0:\n {scores}")

Mask for names not equal to 'Bob': [False  True  True False  True  True  True]
Scores of people not named Bob:
 [[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [  0  80]]

Mask for names equal to 'Bob' or 'Will': [ True False  True  True  True False False]
Scores of people named Bob or Will:
 [[  0  80]
 [ 95 100]
 [100   0]
 [ 85  92]]

Mask for scores less than 80:
 [[ True False]
 [False False]
 [False False]
 [False  True]
 [False False]
 [False False]
 [ True False]]
Score after setting scores less than 80 to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [53]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [[-0.19080897  0.04136637  0.91064561 -1.09075509]
 [-0.16580892 -0.16336972 -0.19932753 -0.42698495]
 [ 0.1559332  -1.34009505  0.07008472 -0.43106417]]

Mean down rows (axis=0): [-0.0668949  -0.48736613  0.2604676  -0.6496014 ]
Sum across columns (axis=1): [-0.32955208 -0.95549112 -1.5451413 ]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [54]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### [EXERCISE 4: Reshaping & Statistics]
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [59]:
#1 
# create an array of 15 intergers
arr_15 = np.arange(15)
print("Array of 15 integers:", arr_15)
#reshape it to a 3x5 array
arr_3x5 = arr_15.reshape(3, 5)
print("Reshaped to 3x5 array:\n", arr_3x5)

#2
# Calculate the average value for each row
row_averages = np.mean(arr_3x5, axis=1)
print("Average value for each row:", row_averages)

#3.as_integer_ratio
# Use np.unique to find distinct elements in an array


#4
# Transpose a 2D array
arr_2d = np.array(arr_3x5)  # using the arr_3x5 from earlier
print("Original 2D array:\n", arr_2d)
arr_transposed = arr_2d.T
print("Transposed array:\n", arr_transposed)

Array of 15 integers: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped to 3x5 array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Average value for each row: [ 2.  7. 12.]
Original 2D array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Transposed array:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
